### ISSUE TITLE
при запуске на виртуальной машине virtualbox или gnome-boxes система утыкается в xdm и просит пароль пользователся

### ISSUE THREAD

**Issue by evgen667** [ctlos/ctlosiso#13]
приветствую, при запуске образа на виртуальной машине выдает вот это оккно, а пароль от учетной записи не извесстин

![Снимок экрана от 2023-08-23 14-09-17](https://github.com/ctlos/ctlosiso/assets/8349669/a1c46931-2d77-4c01-ae1c-5e9c6c395b10)

Использовал virtualbox (bios) и gnome-boxes (как в режиме bios так и  в режиме UEFI)
Как это решается? Причем если запускать на реальном железе все нормально

**Comment by creio** [comment]
в 2.4.4 исправлено. @evgen667
