### ISSUE TITLE
Offline установка ctlos_xfce_2.4.2_20231203.iso

### ISSUE THREAD

**Issue by Rusoid** [ctlos/ctlosiso#14]
Не работает offline установка с последнего образа. Установщик не находит смонтированный образ airootfs. Он копируется в каталог disktoram вроде бы (сейчас не могу посмотреть), что для установщика неожиданно. Online работает норм.

**Comment by creio** [comment]
в 2.4.4 исправлено. @Rusoid

**Comment by Rusoid** [comment]
неа... https://termbin.com/v3d2

**Comment by creio** [comment]
@Rusoid 

я несколько раз ставил и не увидел проблем.
![изображение](https://github.com/ctlos/ctlosiso/assets/20855126/7cb68054-9502-4cc9-8f63-07e8d16d3de7)

**Comment by creio** [comment]
![изображение](https://github.com/ctlos/ctlosiso/assets/20855126/30f48973-49d8-411a-9a53-f25b31bd2b27)
![изображение](https://github.com/ctlos/ctlosiso/assets/20855126/bed42003-2b39-453d-ac0a-1a6b25556aad)
