### ISSUE TITLE
Cannot install by live installer

### ISSUE THREAD

**Issue by EndlessPeak** [ctlos/ctlosiso#4]
Environment: 
Virtualbox
Ctlos bspwm 0.4 
ISO:
ctlos_bspwm_0.4.0_20200919.iso
Description:
After I ran the calamares from drun,it had no response.
I chose to ran it from terminal,it showed the error message as follows.
Would you please tell me how can I fix it and install the system?
![image](https://user-images.githubusercontent.com/53530553/103434533-9915f080-4c3d-11eb-898e-b96eb350faca.jpg)

**Comment by creio** [comment]
Да, я знаю о этой проблеме. Вы легко можете установить bspwm из xfce iso > online > bspwm, там такой проблемы не должно быть с vbox.
